apiVersion: 1

datasources:
  - name: dfpli1tj8oqgwe
    uid: dfpli1tj8oqgwe
    type: postgres
    access: proxy
    url: postgres:5432
    user: portfolio
    secureJsonData:
      password: portfolio
    jsonData:
      database: portfolio
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: true
